### ISSUE TITLE
Non-deterministic failure in web retrieval due to import of twitterscraper

### ISSUE THREAD

**Issue by lapp0** [taspinar/twitterscraper#113]
First time I imported `twitterscraper`, it attempted to make a request, and failed. Making a request when you import the module seems like a bad design.

First time failure:

```
>>> import twitterscraper
Error occurred during loading data. Trying to use cache server http://d2g6u4gh6d9rq0.cloudfront.net/browsers/fake_useragent_0.1.10.json
Traceback (most recent call last):
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/r8yr2d4wrfs3x3cv0gr8vp3blpgwkk6c-python3.6-fake-useragent-nix-0.1.10/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/r8yr2d4wrfs3x3cv0gr8vp3blpgwkk6c-python3.6-fake-useragent-nix-0.1.10/lib/python3.6/site-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/nix/store/r8yr2d4wrfs3x3cv0gr8vp3blpgwkk6c-python3.6-fake-useragent-nix-0.1.10/lib/python3.6/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/nix/store/r8yr2d4wrfs3x3cv0gr8vp3blpgwkk6c-python3.6-fake-useragent-nix-0.1.10/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

The following two times I closed the python interpreter and called `import twitterscraper` it didn't produce an error.

**Comment by CamiloVeloz** [comment]
Good morning @taspinar , I´m having the same issues.

Im working with Ubuntu in 16.04 version and two days ago was perfectly working and today is not extracting any data.
I did the following search:

twitterscraper %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 --lang en -o Executive.json

INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2006-03-21 until:2006-10-29
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2006-10-29 until:2007-06-08
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2007-06-08 until:2008-01-16
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2008-01-16 until:2008-08-26
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2008-08-26 until:2009-04-05
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2009-04-05 until:2009-11-13
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2009-11-13 until:2010-06-24
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2010-06-24 until:2011-02-01
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2011-02-01 until:2011-09-11
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2012-04-21 until:2012-11-29
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2012-11-29 until:2013-07-09
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2013-07-09 until:2014-02-16
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2014-02-16 until:2014-09-27
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2015-12-15 until:2016-07-25
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2016-07-25 until:2017-03-04
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2017-03-04 until:2017-10-12
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2014-09-27 until:2015-05-07
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2015-05-07 until:2015-12-15
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2017-10-12 until:2018-05-23
INFO: Querying %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30 since:2011-09-11 until:2012-04-21
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2007-06-08%20until%3A2008-01-16.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2006-03-21%20until%3A2006-10-29.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2009-11-13%20until%3A2010-06-24.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2012-04-21%20until%3A2012-11-29.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2011-02-01%20until%3A2011-09-11.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2006-10-29%20until%3A2007-06-08.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2009-04-05%20until%3A2009-11-13.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2015-12-15%20until%3A2016-07-25.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2012-11-29%20until%3A2013-07-09.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2013-07-09%20until%3A2014-02-16.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2017-03-04%20until%3A2017-10-12.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2011-09-11%20until%3A2012-04-21.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2016-07-25%20until%3A2017-03-04.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2014-02-16%20until%3A2014-09-27.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2010-06-24%20until%3A2011-02-01.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2008-01-16%20until%3A2008-08-26.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2008-08-26%20until%3A2009-04-05.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2014-09-27%20until%3A2015-05-07.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2015-05-07%20until%3A2015-12-15.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for %23Executiveprotection%20since%3A2018-01-01%20until%3A2018-04-30%20since%3A2017-10-12%20until%3A2018-05-23.

**Comment by lapp0** [comment]
@CamiloVeloz I don't think this is the same issue. Is there some trackback you left out?

**Comment by CamiloVeloz** [comment]
@lapp0  you're right

**Comment by lapp0** [comment]
Closing because fakeuseragent dependency was removed
