### ISSUE TITLE
Significant Reduction in tweetcounts for the queries related to news, tv network 

### ISSUE THREAD

**Issue by NileshJorwar** [taspinar/twitterscraper#124]
I queried as follows:
twitterscraper from:askamex -l 600000 -bd 2006-03-21 -ed 2018-06-23 -o askamex.json
Though I did not get any error but I got only 1832 tweets instead of 538K tweets .

I tried following accounts 

@3MNews
@AbbottNews
@AbercrombieHelp
@AccentureConslt
@AdobeNews
@aflacduck
@AgilentChem

**Comment by lapp0** [comment]
You should try this library which gets from profiles rather than search

https://github.com/kennethreitz/twitter-scraper

**Comment by taspinar** [comment]
@NileshJorwar Since version 0.9.0 it is also possible to scrape tweets from the users profile page. I have tried it with several users with not too many tweets ( ~1000 ) and noticed that it does scrape all tweets, but this is not equal to the written no on their profile page. 
For news agencies it could be that a lot of tweets are deleted and the number of tweets indicated on their profile page is not the actual number of tweets. 
I will close this issue for now.
