### ISSUE TITLE
can't find output

### ISSUE THREAD

**Issue by krishnapsrinivasan** [taspinar/twitterscraper#291]
Hi, i am trying to use the docker version to harvest some tweets, but i cannot find the output (.csv/.json) files. The code i ran is:

`docker run --rm  -it -v/home/krishna/dropbox/:/app/data twitterscraper:build twitterscraper obama --limit 1 --output=obama.json
`

Thank you!

**Comment by YoshiRi** [comment]
Hi I had same problem and solved it.

Just mount the `/app` instead of `/app/data`.

Try: 

`docker run --rm -it -v /home/krishna/dropbox/:/app twitterscraper:build twitterscraper obama --limit 1 --output=obama.json`

or

`docker run --rm -it -v /home/krishna/dropbox/:/app/data twitterscraper:build twitterscraper obama --limit 1 --output=data/obama.json`

**Comment by taspinar** [comment]
@YoshiRi Thank you for answering the question.
