### ISSUE TITLE
Encoding issue when applying the script to non-English language

### ISSUE THREAD

**Issue by zdw-chj** [taspinar/twitterscraper#37]
Dear author
Thanks very much for your kind work! I am a beginner on python programming and hope it would not trouble you too much.
Here is the problem that I am gonna apply the script on mining non-English text (for twitter advanced search page), such as "戦う", while non-English text in the output file is always displayed as unicode like "'\xe7\x8e\xb2\xe9\ ... ..."
even when typing the command "print(tweet.text.encode('utf-8'))"(or with other encode), the output is still the same.
I am wondering if there is some specific measures to display the non-English text correctly?
Thanks!

**Comment by ralfian** [comment]
Same here, i need to mining in non-english text also, please help us.
Thanks!

**Comment by ralfian** [comment]
alternative solution is use location of the non-english city.

**Comment by aliyudin21** [comment]
You can write a script in your Python intepreter like following : 

```
from twitterscraper import query_tweets

for tweet in query_tweets('your keyword', 10)[:10]:
    A = tweet.text.encode('utf-8')
    C = tweet.user.encode('utf-8')
   
    xfile = 'F:/tweets.json'    #you can create your own .json in your own path 
    with open(xfile, 'ab+') as f:    #ab+ is to write in the end position of the file (appending) 
        f.seek(0)
        f.write(A+'\n')    #you need '\n' to make new line for incoming tweets 
        f.write(C+'\n')
```

Hopt it helps.

**Comment by taspinar** [comment]
@zdw-chj @ralfian @aliyudin21 
The twitterscraper as it is, should work properly with non-english characters. 

The thing is, when the text is saved to file, it is saved as the utf-8 encoded bytes of these characters instead of the actual characters. 

So when you scrape for "戦う", the contents of the file will indeed look something like ""\u30b1\u30f3\u3055\u307e\u30fe ..."

so what you should do is open this file with the proper encoding
```
import codecs, json
filename = 'chinese.json'
with codecs.open(filename, 'r', 'utf-8') as f:
    tweets = json.load(f, encoding='utf-8')

```

See example below:
![chinese_characters](https://user-images.githubusercontent.com/4409108/30702318-f05bc196-9eec-11e7-8234-a07aabec294f.PNG)
