### ISSUE TITLE
Issues with since and until in commandline

### ISSUE THREAD

**Issue by a3igner** [taspinar/twitterscraper#42]
twitterscraper "%24PEP"%20since%3A2017-10-05 -o pep.out

this works, but when running it 

twitterscraper "%24PEP"%20since%3A2017-10-05%20until%3A2017-10-05 -o pep.out

it doesnt work.

Ie. i want to limit the results to only one single day. wont' work.

**Comment by taspinar** [comment]
Yes,
twitter itself does not return anything when you set since and until to the same day:
See: https://twitter.com/search?f=tweets&q=%24PEP%22%20since%3A2017-10-05%20until%3A2017-10-05

Best is to set it to the next day and filter the scraped results for the day you want, like:
https://twitter.com/search?f=tweets&q=%24PEP%22%20since%3A2017-10-05%20until%3A2017-10-06
